package info

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"

	"example.com/module/config"
)

func Test_Something(t *testing.T) {

	info_file := &Info_AutoGenerated{}
	info_file.ObtainResults("google.com")
	results, err := info_file.GenerateResults()
	if err != nil {
		assert.Error(t, err, "error!")
	}
	fmt.Println(results)
}

func Test_GenerateUrl(t *testing.T) {
	conf := config.Config{
		ApiKey: "key",
		ApiUrl: "http://example.com/",
		Format: "json",
	}

	value := generateURI(conf, "domain.com")
	assert.Equal(t, value, "http://example.com/apiKey=key&domainName=domain.com&outputFormat=json", "expected URI to match format of expected URI")
}
